Invoke-Command -FilePath "C:\Users\jacob\Desktop\CLaPT\PantherParser\PantherELTParse.ps1"
Invoke-Command -FilePath "C:\Users\jacob\Desktop\CLaPT\PantherParser\PantherSetupActParser.ps1"
Invoke-Command -FilePath "C:\Users\jacob\Desktop\CLaPT\Security Event Log Parsing\EventLogTamper.ps1"
Invoke-Command -FilePath "C:\Users\jacob\Desktop\CLaPT\Security Event Log Parsing\FailedLogon.ps1"
Invoke-Command -FilePath "C:\Users\jacob\Desktop\CLaPT\ObjectAccess.ps1"
Invoke-Command -FilePath "C:\Users\jacob\Desktop\CLaPT\SystemTimeChange.ps1"
Invoke-Command -FilePath "C:\Users\jacob\Desktop\CLaPT\WinLogoff.ps1"
Invoke-Command -FilePath "C:\Users\jacob\Desktop\CLaPT\WinLogon.ps1"
Invoke-Command -FilePath "C:\Users\jacob\Desktop\CLaPT\ShutdownLog.ps1"